# Workflow to deploy website files using SSH and rsync

name: Deploy Website via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Build the Angular project
      # - name: install node.js and build project
        # run: |
          # npm install
          # npm build

      # 2. Deploys files using rsync for efficiency
      - name: Deploy with rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # rsync from the current directory to the server's public_html
            # -a: archive mode, -v: verbose, -z: compress, --delete: remove old files
            rsync -avz --delete ./ public_html/zombietrading.com
            
            # You can also run commands on the server after deploying

            # echo "Deployment complete!"
